version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 992382625926.dkr.ecr.us-east-1.amazonaws.com
  
  build:
    commands:
      - echo Build started on `date`
      - docker build -t build-image-demo .
      - docker tag build-image-demo:latest 992382625926.dkr.ecr.us-east-1.amazonaws.com/bobdocbryan/concepts-build-image-demo:latest
      - docker push 992382625926.dkr.ecr.us-east-1.amazonaws.com/bobdocbryan/concepts-build-image-demo:latest

artifacts:
  files: '**/*'